/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.emailservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.weavrbank.emailservice.EmailService;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link EmailService}.
 * @see EmailService
 */
@RestController
@Api(value = "EmailController", description = "controller class for java service execution")
@RequestMapping("/email")
public class EmailController {

    @Autowired
    private EmailService emailService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @GetMapping(value = "/sendEmailWithTemplate")
    public void sendEmailWithTemplate(@RequestParam(value = "toEmailAddress", required = false) String toEmailAddress, @RequestParam(value = "emailSubject", required = false) String emailSubject) {
        emailService.sendEmailWithTemplate(toEmailAddress, emailSubject);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @GetMapping(value = "/sendMailWithSimpleMessage")
    public void sendMailWithSimpleMessage(@RequestParam(value = "toEmailAddress", required = false) String toEmailAddress, @RequestParam(value = "emailSubject", required = false) String emailSubject, @RequestParam(value = "emailMessage", required = false) String emailMessage) {
        emailService.sendMailWithSimpleMessage(toEmailAddress, emailSubject, emailMessage);
    }
}
