/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.brightbankdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.weavrbank.brightbankdb.models.query.*;

public interface BrightBankDBQueryExecutorService {

    Page<QrGoalTransactionSummryByGoalResponse> executeQrGoalTransactionSummryByGoal(Integer goalId, Pageable pageable);

    void exportQrGoalTransactionSummryByGoal(Integer goalId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QrWealthGoalsListResponse> executeQrWealthGoalsList(String userId, Pageable pageable);

    void exportQrWealthGoalsList(String userId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}
