/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.brightbankdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.weavrbank.brightbankdb.GoalFormFields;


/**
 * ServiceImpl object for domain model class GoalFormFields.
 *
 * @see GoalFormFields
 */
@Service("BrightBankDB.GoalFormFieldsService")
@Validated
@EntityService(entityClass = GoalFormFields.class, serviceId = "BrightBankDB")
public class GoalFormFieldsServiceImpl implements GoalFormFieldsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(GoalFormFieldsServiceImpl.class);


    @Autowired
    @Qualifier("BrightBankDB.GoalFormFieldsDao")
    private WMGenericDao<GoalFormFields, Integer> wmGenericDao;

    @Autowired
    @Qualifier("wmAppObjectMapper")
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<GoalFormFields, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public GoalFormFields create(GoalFormFields goalFormFields) {
        LOGGER.debug("Creating a new GoalFormFields with information: {}", goalFormFields);

        GoalFormFields goalFormFieldsCreated = this.wmGenericDao.create(goalFormFields);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(goalFormFieldsCreated);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public GoalFormFields getById(Integer goalformfieldsId) {
        LOGGER.debug("Finding GoalFormFields by id: {}", goalformfieldsId);
        return this.wmGenericDao.findById(goalformfieldsId);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public GoalFormFields findById(Integer goalformfieldsId) {
        LOGGER.debug("Finding GoalFormFields by id: {}", goalformfieldsId);
        try {
            return this.wmGenericDao.findById(goalformfieldsId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No GoalFormFields found with id: {}", goalformfieldsId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public List<GoalFormFields> findByMultipleIds(List<Integer> goalformfieldsIds, boolean orderedReturn) {
        LOGGER.debug("Finding GoalFormFields by ids: {}", goalformfieldsIds);

        return this.wmGenericDao.findByMultipleIds(goalformfieldsIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "BrightBankDBTransactionManager")
    @Override
    public GoalFormFields update(GoalFormFields goalFormFields) {
        LOGGER.debug("Updating GoalFormFields with information: {}", goalFormFields);

        this.wmGenericDao.update(goalFormFields);
        this.wmGenericDao.refresh(goalFormFields);

        return goalFormFields;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public GoalFormFields partialUpdate(Integer goalformfieldsId, Map<String, Object>goalFormFieldsPatch) {
        LOGGER.debug("Partially Updating the GoalFormFields with id: {}", goalformfieldsId);

        GoalFormFields goalFormFields = getById(goalformfieldsId);

        try {
            ObjectReader goalFormFieldsReader = this.objectMapper.reader().forType(GoalFormFields.class).withValueToUpdate(goalFormFields);
            goalFormFields = goalFormFieldsReader.readValue(this.objectMapper.writeValueAsString(goalFormFieldsPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", goalFormFieldsPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        goalFormFields = update(goalFormFields);

        return goalFormFields;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public GoalFormFields delete(Integer goalformfieldsId) {
        LOGGER.debug("Deleting GoalFormFields with id: {}", goalformfieldsId);
        GoalFormFields deleted = this.wmGenericDao.findById(goalformfieldsId);
        if (deleted == null) {
            LOGGER.debug("No GoalFormFields found with id: {}", goalformfieldsId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), GoalFormFields.class.getSimpleName(), goalformfieldsId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public void delete(GoalFormFields goalFormFields) {
        LOGGER.debug("Deleting GoalFormFields with {}", goalFormFields);
        this.wmGenericDao.delete(goalFormFields);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public Page<GoalFormFields> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all GoalFormFields");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public Page<GoalFormFields> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all GoalFormFields");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service BrightBankDB for table GoalFormFields to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service BrightBankDB for table GoalFormFields to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
