/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.brightbankdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.weavrbank.brightbankdb.GoalFormFields;

/**
 * Service object for domain model class {@link GoalFormFields}.
 */
public interface GoalFormFieldsService {

    /**
     * Creates a new GoalFormFields. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on GoalFormFields if any.
     *
     * @param goalFormFields Details of the GoalFormFields to be created; value cannot be null.
     * @return The newly created GoalFormFields.
     */
    GoalFormFields create(@Valid GoalFormFields goalFormFields);


	/**
     * Returns GoalFormFields by given id if exists.
     *
     * @param goalformfieldsId The id of the GoalFormFields to get; value cannot be null.
     * @return GoalFormFields associated with the given goalformfieldsId.
	 * @throws EntityNotFoundException If no GoalFormFields is found.
     */
    GoalFormFields getById(Integer goalformfieldsId);

    /**
     * Find and return the GoalFormFields by given id if exists, returns null otherwise.
     *
     * @param goalformfieldsId The id of the GoalFormFields to get; value cannot be null.
     * @return GoalFormFields associated with the given goalformfieldsId.
     */
    GoalFormFields findById(Integer goalformfieldsId);

	/**
     * Find and return the list of GoalFormFields by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param goalformfieldsIds The id's of the GoalFormFields to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return GoalFormFields associated with the given goalformfieldsIds.
     */
    List<GoalFormFields> findByMultipleIds(List<Integer> goalformfieldsIds, boolean orderedReturn);


    /**
     * Updates the details of an existing GoalFormFields. It replaces all fields of the existing GoalFormFields with the given goalFormFields.
     *
     * This method overrides the input field values using Server side or database managed properties defined on GoalFormFields if any.
     *
     * @param goalFormFields The details of the GoalFormFields to be updated; value cannot be null.
     * @return The updated GoalFormFields.
     * @throws EntityNotFoundException if no GoalFormFields is found with given input.
     */
    GoalFormFields update(@Valid GoalFormFields goalFormFields);


    /**
     * Partially updates the details of an existing GoalFormFields. It updates only the
     * fields of the existing GoalFormFields which are passed in the goalFormFieldsPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on GoalFormFields if any.
     *
     * @param goalformfieldsId The id of the GoalFormFields to be deleted; value cannot be null.
     * @param goalFormFieldsPatch The partial data of GoalFormFields which is supposed to be updated; value cannot be null.
     * @return The updated GoalFormFields.
     * @throws EntityNotFoundException if no GoalFormFields is found with given input.
     */
    GoalFormFields partialUpdate(Integer goalformfieldsId, Map<String, Object> goalFormFieldsPatch);

    /**
     * Deletes an existing GoalFormFields with the given id.
     *
     * @param goalformfieldsId The id of the GoalFormFields to be deleted; value cannot be null.
     * @return The deleted GoalFormFields.
     * @throws EntityNotFoundException if no GoalFormFields found with the given id.
     */
    GoalFormFields delete(Integer goalformfieldsId);

    /**
     * Deletes an existing GoalFormFields with the given object.
     *
     * @param goalFormFields The instance of the GoalFormFields to be deleted; value cannot be null.
     */
    void delete(GoalFormFields goalFormFields);

    /**
     * Find all GoalFormFields matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching GoalFormFields.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<GoalFormFields> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all GoalFormFields matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching GoalFormFields.
     *
     * @see Pageable
     * @see Page
     */
    Page<GoalFormFields> findAll(String query, Pageable pageable);

    /**
     * Exports all GoalFormFields matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all GoalFormFields matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the GoalFormFields in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the GoalFormFields.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
