/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.brightbankdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.weavrbank.brightbankdb.ListTransaction;

/**
 * Service object for domain model class {@link ListTransaction}.
 */
public interface ListTransactionService {

    /**
     * Creates a new ListTransaction. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ListTransaction if any.
     *
     * @param listTransaction Details of the ListTransaction to be created; value cannot be null.
     * @return The newly created ListTransaction.
     */
    ListTransaction create(@Valid ListTransaction listTransaction);


	/**
     * Returns ListTransaction by given id if exists.
     *
     * @param listtransactionId The id of the ListTransaction to get; value cannot be null.
     * @return ListTransaction associated with the given listtransactionId.
	 * @throws EntityNotFoundException If no ListTransaction is found.
     */
    ListTransaction getById(Integer listtransactionId);

    /**
     * Find and return the ListTransaction by given id if exists, returns null otherwise.
     *
     * @param listtransactionId The id of the ListTransaction to get; value cannot be null.
     * @return ListTransaction associated with the given listtransactionId.
     */
    ListTransaction findById(Integer listtransactionId);

	/**
     * Find and return the list of ListTransactions by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param listtransactionIds The id's of the ListTransaction to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return ListTransactions associated with the given listtransactionIds.
     */
    List<ListTransaction> findByMultipleIds(List<Integer> listtransactionIds, boolean orderedReturn);


    /**
     * Updates the details of an existing ListTransaction. It replaces all fields of the existing ListTransaction with the given listTransaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ListTransaction if any.
     *
     * @param listTransaction The details of the ListTransaction to be updated; value cannot be null.
     * @return The updated ListTransaction.
     * @throws EntityNotFoundException if no ListTransaction is found with given input.
     */
    ListTransaction update(@Valid ListTransaction listTransaction);


    /**
     * Partially updates the details of an existing ListTransaction. It updates only the
     * fields of the existing ListTransaction which are passed in the listTransactionPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ListTransaction if any.
     *
     * @param listtransactionId The id of the ListTransaction to be deleted; value cannot be null.
     * @param listTransactionPatch The partial data of ListTransaction which is supposed to be updated; value cannot be null.
     * @return The updated ListTransaction.
     * @throws EntityNotFoundException if no ListTransaction is found with given input.
     */
    ListTransaction partialUpdate(Integer listtransactionId, Map<String, Object> listTransactionPatch);

    /**
     * Deletes an existing ListTransaction with the given id.
     *
     * @param listtransactionId The id of the ListTransaction to be deleted; value cannot be null.
     * @return The deleted ListTransaction.
     * @throws EntityNotFoundException if no ListTransaction found with the given id.
     */
    ListTransaction delete(Integer listtransactionId);

    /**
     * Deletes an existing ListTransaction with the given object.
     *
     * @param listTransaction The instance of the ListTransaction to be deleted; value cannot be null.
     */
    void delete(ListTransaction listTransaction);

    /**
     * Find all ListTransactions matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ListTransactions.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<ListTransaction> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all ListTransactions matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ListTransactions.
     *
     * @see Pageable
     * @see Page
     */
    Page<ListTransaction> findAll(String query, Pageable pageable);

    /**
     * Exports all ListTransactions matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all ListTransactions matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the ListTransactions in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the ListTransaction.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
