/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.brightbankdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.weavrbank.brightbankdb.Themedetail;
import com.weavrbank.brightbankdb.Themetype;

/**
 * Service object for domain model class {@link Themetype}.
 */
public interface ThemetypeService {

    /**
     * Creates a new Themetype. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Themetype if any.
     *
     * @param themetype Details of the Themetype to be created; value cannot be null.
     * @return The newly created Themetype.
     */
    Themetype create(@Valid Themetype themetype);


	/**
     * Returns Themetype by given id if exists.
     *
     * @param themetypeId The id of the Themetype to get; value cannot be null.
     * @return Themetype associated with the given themetypeId.
	 * @throws EntityNotFoundException If no Themetype is found.
     */
    Themetype getById(Integer themetypeId);

    /**
     * Find and return the Themetype by given id if exists, returns null otherwise.
     *
     * @param themetypeId The id of the Themetype to get; value cannot be null.
     * @return Themetype associated with the given themetypeId.
     */
    Themetype findById(Integer themetypeId);

	/**
     * Find and return the list of Themetypes by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param themetypeIds The id's of the Themetype to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Themetypes associated with the given themetypeIds.
     */
    List<Themetype> findByMultipleIds(List<Integer> themetypeIds, boolean orderedReturn);


    /**
     * Updates the details of an existing Themetype. It replaces all fields of the existing Themetype with the given themetype.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Themetype if any.
     *
     * @param themetype The details of the Themetype to be updated; value cannot be null.
     * @return The updated Themetype.
     * @throws EntityNotFoundException if no Themetype is found with given input.
     */
    Themetype update(@Valid Themetype themetype);


    /**
     * Partially updates the details of an existing Themetype. It updates only the
     * fields of the existing Themetype which are passed in the themetypePatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Themetype if any.
     *
     * @param themetypeId The id of the Themetype to be deleted; value cannot be null.
     * @param themetypePatch The partial data of Themetype which is supposed to be updated; value cannot be null.
     * @return The updated Themetype.
     * @throws EntityNotFoundException if no Themetype is found with given input.
     */
    Themetype partialUpdate(Integer themetypeId, Map<String, Object> themetypePatch);

    /**
     * Deletes an existing Themetype with the given id.
     *
     * @param themetypeId The id of the Themetype to be deleted; value cannot be null.
     * @return The deleted Themetype.
     * @throws EntityNotFoundException if no Themetype found with the given id.
     */
    Themetype delete(Integer themetypeId);

    /**
     * Deletes an existing Themetype with the given object.
     *
     * @param themetype The instance of the Themetype to be deleted; value cannot be null.
     */
    void delete(Themetype themetype);

    /**
     * Find all Themetypes matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Themetypes.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Themetype> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Themetypes matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Themetypes.
     *
     * @see Pageable
     * @see Page
     */
    Page<Themetype> findAll(String query, Pageable pageable);

    /**
     * Exports all Themetypes matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Themetypes matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Themetypes in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Themetype.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated themedetails for given Themetype id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Themedetail instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Themedetail> findAssociatedThemedetails(Integer id, Pageable pageable);

}
