/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.brightbankdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.weavrbank.brightbankdb.ThemeConfig;


/**
 * ServiceImpl object for domain model class ThemeConfig.
 *
 * @see ThemeConfig
 */
@Service("BrightBankDB.ThemeConfigService")
@Validated
@EntityService(entityClass = ThemeConfig.class, serviceId = "BrightBankDB")
public class ThemeConfigServiceImpl implements ThemeConfigService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ThemeConfigServiceImpl.class);


    @Autowired
    @Qualifier("BrightBankDB.ThemeConfigDao")
    private WMGenericDao<ThemeConfig, Integer> wmGenericDao;

    @Autowired
    @Qualifier("wmAppObjectMapper")
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<ThemeConfig, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public ThemeConfig create(ThemeConfig themeConfig) {
        LOGGER.debug("Creating a new ThemeConfig with information: {}", themeConfig);

        ThemeConfig themeConfigCreated = this.wmGenericDao.create(themeConfig);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(themeConfigCreated);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public ThemeConfig getById(Integer themeconfigId) {
        LOGGER.debug("Finding ThemeConfig by id: {}", themeconfigId);
        return this.wmGenericDao.findById(themeconfigId);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public ThemeConfig findById(Integer themeconfigId) {
        LOGGER.debug("Finding ThemeConfig by id: {}", themeconfigId);
        try {
            return this.wmGenericDao.findById(themeconfigId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No ThemeConfig found with id: {}", themeconfigId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public List<ThemeConfig> findByMultipleIds(List<Integer> themeconfigIds, boolean orderedReturn) {
        LOGGER.debug("Finding ThemeConfigs by ids: {}", themeconfigIds);

        return this.wmGenericDao.findByMultipleIds(themeconfigIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "BrightBankDBTransactionManager")
    @Override
    public ThemeConfig update(ThemeConfig themeConfig) {
        LOGGER.debug("Updating ThemeConfig with information: {}", themeConfig);

        this.wmGenericDao.update(themeConfig);
        this.wmGenericDao.refresh(themeConfig);

        return themeConfig;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public ThemeConfig partialUpdate(Integer themeconfigId, Map<String, Object>themeConfigPatch) {
        LOGGER.debug("Partially Updating the ThemeConfig with id: {}", themeconfigId);

        ThemeConfig themeConfig = getById(themeconfigId);

        try {
            ObjectReader themeConfigReader = this.objectMapper.reader().forType(ThemeConfig.class).withValueToUpdate(themeConfig);
            themeConfig = themeConfigReader.readValue(this.objectMapper.writeValueAsString(themeConfigPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", themeConfigPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        themeConfig = update(themeConfig);

        return themeConfig;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public ThemeConfig delete(Integer themeconfigId) {
        LOGGER.debug("Deleting ThemeConfig with id: {}", themeconfigId);
        ThemeConfig deleted = this.wmGenericDao.findById(themeconfigId);
        if (deleted == null) {
            LOGGER.debug("No ThemeConfig found with id: {}", themeconfigId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), ThemeConfig.class.getSimpleName(), themeconfigId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "BrightBankDBTransactionManager")
    @Override
    public void delete(ThemeConfig themeConfig) {
        LOGGER.debug("Deleting ThemeConfig with {}", themeConfig);
        this.wmGenericDao.delete(themeConfig);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public Page<ThemeConfig> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all ThemeConfigs");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public Page<ThemeConfig> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all ThemeConfigs");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service BrightBankDB for table ThemeConfig to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service BrightBankDB for table ThemeConfig to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "BrightBankDBTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
