/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.weavrbank.brightbankdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.weavrbank.brightbankdb.GoalTransactions;
import com.weavrbank.brightbankdb.WealthGoals;

/**
 * Service object for domain model class {@link WealthGoals}.
 */
public interface WealthGoalsService {

    /**
     * Creates a new WealthGoals. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on WealthGoals if any.
     *
     * @param wealthGoals Details of the WealthGoals to be created; value cannot be null.
     * @return The newly created WealthGoals.
     */
    WealthGoals create(@Valid WealthGoals wealthGoals);


	/**
     * Returns WealthGoals by given id if exists.
     *
     * @param wealthgoalsId The id of the WealthGoals to get; value cannot be null.
     * @return WealthGoals associated with the given wealthgoalsId.
	 * @throws EntityNotFoundException If no WealthGoals is found.
     */
    WealthGoals getById(Integer wealthgoalsId);

    /**
     * Find and return the WealthGoals by given id if exists, returns null otherwise.
     *
     * @param wealthgoalsId The id of the WealthGoals to get; value cannot be null.
     * @return WealthGoals associated with the given wealthgoalsId.
     */
    WealthGoals findById(Integer wealthgoalsId);

	/**
     * Find and return the list of WealthGoals by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param wealthgoalsIds The id's of the WealthGoals to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return WealthGoals associated with the given wealthgoalsIds.
     */
    List<WealthGoals> findByMultipleIds(List<Integer> wealthgoalsIds, boolean orderedReturn);


    /**
     * Updates the details of an existing WealthGoals. It replaces all fields of the existing WealthGoals with the given wealthGoals.
     *
     * This method overrides the input field values using Server side or database managed properties defined on WealthGoals if any.
     *
     * @param wealthGoals The details of the WealthGoals to be updated; value cannot be null.
     * @return The updated WealthGoals.
     * @throws EntityNotFoundException if no WealthGoals is found with given input.
     */
    WealthGoals update(@Valid WealthGoals wealthGoals);


    /**
     * Partially updates the details of an existing WealthGoals. It updates only the
     * fields of the existing WealthGoals which are passed in the wealthGoalsPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on WealthGoals if any.
     *
     * @param wealthgoalsId The id of the WealthGoals to be deleted; value cannot be null.
     * @param wealthGoalsPatch The partial data of WealthGoals which is supposed to be updated; value cannot be null.
     * @return The updated WealthGoals.
     * @throws EntityNotFoundException if no WealthGoals is found with given input.
     */
    WealthGoals partialUpdate(Integer wealthgoalsId, Map<String, Object> wealthGoalsPatch);

    /**
     * Deletes an existing WealthGoals with the given id.
     *
     * @param wealthgoalsId The id of the WealthGoals to be deleted; value cannot be null.
     * @return The deleted WealthGoals.
     * @throws EntityNotFoundException if no WealthGoals found with the given id.
     */
    WealthGoals delete(Integer wealthgoalsId);

    /**
     * Deletes an existing WealthGoals with the given object.
     *
     * @param wealthGoals The instance of the WealthGoals to be deleted; value cannot be null.
     */
    void delete(WealthGoals wealthGoals);

    /**
     * Find all WealthGoals matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching WealthGoals.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<WealthGoals> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all WealthGoals matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching WealthGoals.
     *
     * @see Pageable
     * @see Page
     */
    Page<WealthGoals> findAll(String query, Pageable pageable);

    /**
     * Exports all WealthGoals matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all WealthGoals matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the WealthGoals in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the WealthGoals.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated goalTransactionses for given WealthGoals id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated GoalTransactions instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<GoalTransactions> findAssociatedGoalTransactionses(Integer id, Pageable pageable);

}
