/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.getThemeProperties.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseCssproperty
 */

public class ResponseCssproperty {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("cssvariable")
  private String cssvariable = null;

  public ResponseCssproperty name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResponseCssproperty id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ResponseCssproperty cssvariable(String cssvariable) {
    this.cssvariable = cssvariable;
    return this;
  }

   /**
   * Get cssvariable
   * @return cssvariable
  **/
  public String getCssvariable() {
    return cssvariable;
  }

  public void setCssvariable(String cssvariable) {
    this.cssvariable = cssvariable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCssproperty Response_cssproperty = (ResponseCssproperty) o;
    return Objects.equals(this.name, Response_cssproperty.name) &&
        Objects.equals(this.id, Response_cssproperty.id) &&
        Objects.equals(this.cssvariable, Response_cssproperty.cssvariable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, cssvariable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCssproperty {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cssvariable: ").append(toIndentedString(cssvariable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
