/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.29.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse2001
 */

public class InlineResponse2001 {
  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("kycLevel")
  private String kycLevel = null;

  public InlineResponse2001 reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * The reference used to initialise the KYC UI Component.
   * @return reference
  **/
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public InlineResponse2001 kycLevel(String kycLevel) {
    this.kycLevel = kycLevel;
    return this;
  }

   /**
   * Get kycLevel
   * @return kycLevel
  **/
  public String getKycLevel() {
    return kycLevel;
  }

  public void setKycLevel(String kycLevel) {
    this.kycLevel = kycLevel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inline_response_200_1 = (InlineResponse2001) o;
    return Objects.equals(this.reference, inline_response_200_1.reference) &&
        Objects.equals(this.kycLevel, inline_response_200_1.kycLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reference, kycLevel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    kycLevel: ").append(toIndentedString(kycLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
