/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.29.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * MerchantData
 */

public class MerchantData {
  @JsonProperty("merchantCity")
  private String merchantCity = null;

  @JsonProperty("merchantDescription")
  private String merchantDescription = null;

  @JsonProperty("merchantContact")
  private String merchantContact = null;

  @JsonProperty("merchantState")
  private String merchantState = null;

  @JsonProperty("merchantTelephone")
  private String merchantTelephone = null;

  @JsonProperty("merchantName")
  private String merchantName = null;

  @JsonProperty("merchantNameOther")
  private String merchantNameOther = null;

  @JsonProperty("merchantStreet")
  private String merchantStreet = null;

  @JsonProperty("merchantId")
  private String merchantId = null;

  @JsonProperty("merchantCategoryCode")
  private String merchantCategoryCode = null;

  @JsonProperty("merchantPostalCode")
  private String merchantPostalCode = null;

  @JsonProperty("merchantNetworkId")
  private String merchantNetworkId = null;

  @JsonProperty("merchantCountry")
  private String merchantCountry = null;

  @JsonProperty("merchantURL")
  private String merchantURL = null;

  public MerchantData merchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
    return this;
  }

   /**
   * The merchant city (if available)
   * @return merchantCity
  **/
  public String getMerchantCity() {
    return merchantCity;
  }

  public void setMerchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
  }

  public MerchantData merchantDescription(String merchantDescription) {
    this.merchantDescription = merchantDescription;
    return this;
  }

   /**
   * The merchant description
   * @return merchantDescription
  **/
  public String getMerchantDescription() {
    return merchantDescription;
  }

  public void setMerchantDescription(String merchantDescription) {
    this.merchantDescription = merchantDescription;
  }

  public MerchantData merchantContact(String merchantContact) {
    this.merchantContact = merchantContact;
    return this;
  }

   /**
   * The merchant&#x27;s contact (if available)
   * @return merchantContact
  **/
  public String getMerchantContact() {
    return merchantContact;
  }

  public void setMerchantContact(String merchantContact) {
    this.merchantContact = merchantContact;
  }

  public MerchantData merchantState(String merchantState) {
    this.merchantState = merchantState;
    return this;
  }

   /**
   * The merchant state address (if available)
   * @return merchantState
  **/
  public String getMerchantState() {
    return merchantState;
  }

  public void setMerchantState(String merchantState) {
    this.merchantState = merchantState;
  }

  public MerchantData merchantTelephone(String merchantTelephone) {
    this.merchantTelephone = merchantTelephone;
    return this;
  }

   /**
   * The merchant telephone number
   * @return merchantTelephone
  **/
  public String getMerchantTelephone() {
    return merchantTelephone;
  }

  public void setMerchantTelephone(String merchantTelephone) {
    this.merchantTelephone = merchantTelephone;
  }

  public MerchantData merchantName(String merchantName) {
    this.merchantName = merchantName;
    return this;
  }

   /**
   * The name of the merchant where the authorisation has been made.
   * @return merchantName
  **/
  public String getMerchantName() {
    return merchantName;
  }

  public void setMerchantName(String merchantName) {
    this.merchantName = merchantName;
  }

  public MerchantData merchantNameOther(String merchantNameOther) {
    this.merchantNameOther = merchantNameOther;
    return this;
  }

   /**
   * The alternative merchant name
   * @return merchantNameOther
  **/
  public String getMerchantNameOther() {
    return merchantNameOther;
  }

  public void setMerchantNameOther(String merchantNameOther) {
    this.merchantNameOther = merchantNameOther;
  }

  public MerchantData merchantStreet(String merchantStreet) {
    this.merchantStreet = merchantStreet;
    return this;
  }

   /**
   * The merchant street address (if available)
   * @return merchantStreet
  **/
  public String getMerchantStreet() {
    return merchantStreet;
  }

  public void setMerchantStreet(String merchantStreet) {
    this.merchantStreet = merchantStreet;
  }

  public MerchantData merchantId(String merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * The merchant ID.
   * @return merchantId
  **/
  public String getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }

  public MerchantData merchantCategoryCode(String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
    return this;
  }

   /**
   * The merchant category code.
   * @return merchantCategoryCode
  **/
  public String getMerchantCategoryCode() {
    return merchantCategoryCode;
  }

  public void setMerchantCategoryCode(String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
  }

  public MerchantData merchantPostalCode(String merchantPostalCode) {
    this.merchantPostalCode = merchantPostalCode;
    return this;
  }

   /**
   * The merchant postal code (if available)
   * @return merchantPostalCode
  **/
  public String getMerchantPostalCode() {
    return merchantPostalCode;
  }

  public void setMerchantPostalCode(String merchantPostalCode) {
    this.merchantPostalCode = merchantPostalCode;
  }

  public MerchantData merchantNetworkId(String merchantNetworkId) {
    this.merchantNetworkId = merchantNetworkId;
    return this;
  }

   /**
   * The merchant&#x27;s network id
   * @return merchantNetworkId
  **/
  public String getMerchantNetworkId() {
    return merchantNetworkId;
  }

  public void setMerchantNetworkId(String merchantNetworkId) {
    this.merchantNetworkId = merchantNetworkId;
  }

  public MerchantData merchantCountry(String merchantCountry) {
    this.merchantCountry = merchantCountry;
    return this;
  }

   /**
   * The merchant country address
   * @return merchantCountry
  **/
  public String getMerchantCountry() {
    return merchantCountry;
  }

  public void setMerchantCountry(String merchantCountry) {
    this.merchantCountry = merchantCountry;
  }

  public MerchantData merchantURL(String merchantURL) {
    this.merchantURL = merchantURL;
    return this;
  }

   /**
   * The merchant URL
   * @return merchantURL
  **/
  public String getMerchantURL() {
    return merchantURL;
  }

  public void setMerchantURL(String merchantURL) {
    this.merchantURL = merchantURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantData MerchantData = (MerchantData) o;
    return Objects.equals(this.merchantCity, MerchantData.merchantCity) &&
        Objects.equals(this.merchantDescription, MerchantData.merchantDescription) &&
        Objects.equals(this.merchantContact, MerchantData.merchantContact) &&
        Objects.equals(this.merchantState, MerchantData.merchantState) &&
        Objects.equals(this.merchantTelephone, MerchantData.merchantTelephone) &&
        Objects.equals(this.merchantName, MerchantData.merchantName) &&
        Objects.equals(this.merchantNameOther, MerchantData.merchantNameOther) &&
        Objects.equals(this.merchantStreet, MerchantData.merchantStreet) &&
        Objects.equals(this.merchantId, MerchantData.merchantId) &&
        Objects.equals(this.merchantCategoryCode, MerchantData.merchantCategoryCode) &&
        Objects.equals(this.merchantPostalCode, MerchantData.merchantPostalCode) &&
        Objects.equals(this.merchantNetworkId, MerchantData.merchantNetworkId) &&
        Objects.equals(this.merchantCountry, MerchantData.merchantCountry) &&
        Objects.equals(this.merchantURL, MerchantData.merchantURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantCity, merchantDescription, merchantContact, merchantState, merchantTelephone, merchantName, merchantNameOther, merchantStreet, merchantId, merchantCategoryCode, merchantPostalCode, merchantNetworkId, merchantCountry, merchantURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantData {\n");
    
    sb.append("    merchantCity: ").append(toIndentedString(merchantCity)).append("\n");
    sb.append("    merchantDescription: ").append(toIndentedString(merchantDescription)).append("\n");
    sb.append("    merchantContact: ").append(toIndentedString(merchantContact)).append("\n");
    sb.append("    merchantState: ").append(toIndentedString(merchantState)).append("\n");
    sb.append("    merchantTelephone: ").append(toIndentedString(merchantTelephone)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    merchantNameOther: ").append(toIndentedString(merchantNameOther)).append("\n");
    sb.append("    merchantStreet: ").append(toIndentedString(merchantStreet)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
    sb.append("    merchantPostalCode: ").append(toIndentedString(merchantPostalCode)).append("\n");
    sb.append("    merchantNetworkId: ").append(toIndentedString(merchantNetworkId)).append("\n");
    sb.append("    merchantCountry: ").append(toIndentedString(merchantCountry)).append("\n");
    sb.append("    merchantURL: ").append(toIndentedString(merchantURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
