/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.29.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * Bank details used in case the wire transfer is executed over SEPA.
 */

public class SepaBankDetails {
  @JsonProperty("iban")
  private String iban = null;

  @JsonProperty("bankIdentifierCode")
  private String bankIdentifierCode = null;

  public SepaBankDetails iban(String iban) {
    this.iban = iban;
    return this;
  }

   /**
   * International Bank Account Number, required for wire transfer over SEPA.
   * @return iban
  **/
  public String getIban() {
    return iban;
  }

  public void setIban(String iban) {
    this.iban = iban;
  }

  public SepaBankDetails bankIdentifierCode(String bankIdentifierCode) {
    this.bankIdentifierCode = bankIdentifierCode;
    return this;
  }

   /**
   * BIC, required for wire transfer over SEPA.
   * @return bankIdentifierCode
  **/
  public String getBankIdentifierCode() {
    return bankIdentifierCode;
  }

  public void setBankIdentifierCode(String bankIdentifierCode) {
    this.bankIdentifierCode = bankIdentifierCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SepaBankDetails SepaBankDetails = (SepaBankDetails) o;
    return Objects.equals(this.iban, SepaBankDetails.iban) &&
        Objects.equals(this.bankIdentifierCode, SepaBankDetails.bankIdentifierCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iban, bankIdentifierCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SepaBankDetails {\n");
    
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    bankIdentifierCode: ").append(toIndentedString(bankIdentifierCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
