/*Generated by WaveMaker Studio*/

package com.custom.security;

import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Arrays;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.AuthenticationException;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.jayway.jsonpath.JsonPath;
import com.wavemaker.runtime.rest.RequestContext;
import com.wavemaker.runtime.rest.RestExecutor;
import com.wavemaker.runtime.security.AuthRequestContext;
import com.wavemaker.runtime.security.WMCustomAuthenticationManager;
import com.wavemaker.runtime.security.WMUser;
import com.weavrbank.weavrLogin.model.IdentityId;
import com.weavrbank.weavrLogin.model.InlineResponse2002;
import com.weavrbank.weavrLogin.model.InlineResponse2003;
import com.weavrbank.weavrLogin.model.LoginWithPasswordBody;
import com.weavrbank.weavrLogin.model.SensitivePassword;
import com.weavrbank.weavrLogin.model.UserIdCreateBody;
import com.weavrbank.weavrLogin.service.AccessService;
import com.weavrbank.weavrLogin.service.PasswordsService;

public class CustomSecurity implements WMCustomAuthenticationManager{

//
    private static final Logger logger = LoggerFactory.getLogger(CustomSecurity.class);

    private static final ObjectMapper objectMapper = new ObjectMapper();

    @Autowired
    private PasswordsService passwordsService;

    @Autowired
    private AccessService accessService;

    @Autowired
    private RestExecutor restExecutor;

    @Value("${app.environment.apikey}")
    private String weavrAPIKey;

    @Value("${app.environment.consumer_profile_id}")
    private String consumerId;
    
    @Value("${app.environment.admin_users_list}")
    private String admin_users_list;

    public WMUser authenticate(AuthRequestContext authRequestContext) throws AuthenticationException {
        logger.info("----- Authentication start------");
        String username = authRequestContext.getUsername();
        String password = authRequestContext.getPassword();
        logger.info("----------User Details: " + username + " password: " + password);
        String userId = authRequestContext.getHttpServletRequest().getHeader("UserId");
        if (userId != null) {
            logger.info("---UserId: {}", userId);
            UserIdCreateBody passwordCreate = new UserIdCreateBody();
            SensitivePassword pwdInfo = new SensitivePassword();
            pwdInfo.setValue(password);
            passwordCreate.setPassword(pwdInfo);
            logger.info("--Request password constructed---");
            InlineResponse2003 response = restExecutor.executeWithContext(
                    RequestContext.Builder.newInstance().addHeader("api-key", weavrAPIKey).addHeader("Content-Type", "application/json").build(), () -> passwordsService.passwordCreate(passwordCreate, userId));
            List<String> roles = new LinkedList<>();
             //temporarily commentes adding getToken and added role for demo 
            // roles.add(response.getToken());
            List<String> usersList = Arrays.asList(admin_users_list.split(","));
            if (usersList.contains(username)) {
                roles.add("Admin");
            } else {
                roles.add("User");
            }
            WMUser wmUser = new WMUser("CONSUMER", roles);
            wmUser.setUserId(response.getPasswordInfo().getIdentityId().getId());
            wmUser.setCustomAttributes(new LinkedHashMap<String, Object>() {{
                put("userType", "NEW");
                put("authtoken", response.getToken());
            }});
            wmUser.setTenantId(1); // setting 1 as tenantId for new user login
            return wmUser;
        } else {
            LoginWithPasswordBody loginInfo = new LoginWithPasswordBody();
            loginInfo.setEmail(username);
            SensitivePassword passwordInfo = new SensitivePassword();
            passwordInfo.setValue(password);
            loginInfo.setPassword(passwordInfo);
            // loginInfo.setIdentity(new IdentityId().id(consumerId).type(IdentityId.TypeEnum.CONSUMER));
            logger.info("-----Service info: " + loginInfo.toString() + weavrAPIKey);
            InlineResponse2002 response = restExecutor.executeWithContext(
                    RequestContext.Builder.newInstance().addHeader("api-key", weavrAPIKey).addHeader("Content-Type", "application/json").build(),
                    () -> accessService.loginWithPassword(loginInfo));
            List<String> roles = new LinkedList<>();
            //temporarily commentes adding getToken and added role for demo 
            // roles.add(response.getToken());
            List<String> usersList = Arrays.asList(admin_users_list.split(","));
            if (usersList.contains(username)) {
                roles.add("Admin");
            } else {
                roles.add("User");
            }
            WMUser wmUser = new WMUser("CONSUMER", roles);
            wmUser.setUserId(response.getIdentity().getId());
            wmUser.setCustomAttributes(new LinkedHashMap<String, Object>() {{
                put("userType", "EXISTING");
                put("authtoken", response.getToken());
            }});
            wmUser.setTenantId(2);
            return wmUser;
        }
    }
}
